(() => {
  'use strict';
  const W = 360, H = 640, GROUND = 92;
  const State = Object.freeze({ MENU:'menu', READY:'ready', PLAYING:'playing', PAUSED:'paused', OVER:'over' });
  const $ = id => document.getElementById(id);
  const canvas = $('game'), ctx = canvas.getContext('2d');
  const el = { menu:$('menu'), ready:$('ready'), layer:$('modalLayer'), hud:$('hud'), score:$('score'), pop:$('scorePop'), best:$('menuBest'), sound:$('soundBtn'), musicBtn:$('musicBtn'), pause:$('pauseBtn'), how:$('howModal'), settings:$('settingsModal'), shop:$('shopModal'), paused:$('pauseModal'), over:$('overModal'), finalScore:$('finalScore'), finalBest:$('finalBest'), newBest:$('newBest'), medal:$('medal'), coinHud:$('coinHud'), coinCount:$('coinCount'), shopCoins:$('shopCoins'), shopTabs:$('shopTabs'), skinList:$('skinList'), soundToggle:$('soundToggle'), musicToggle:$('musicToggle'), difficultyBtn:$('difficultyBtn'), difficultyValue:$('difficultyValue'), difficultyMenu:$('difficultyMenu') };
  const storage = { get(k, d) { try { const v = localStorage.getItem(k); return v === null ? d : JSON.parse(v); } catch (_) { return d; } }, set(k,v) { try { localStorage.setItem(k,JSON.stringify(v)); } catch (_) {} } };
  const settings = storage.get('skyFlappySettings', { sound:true, music:true, difficulty:'normal' });
  const skins = { classic:{name:'CLASSIC',cost:0,body:'#ffd74c',wing:'#f4a62b',beak:'#f79831',trail:'#fff5b2',death:[523,494,440,349,262]}, rose:{name:'ROSE',cost:20,body:'#ff8dab',wing:'#e85d87',beak:'#ffb15b',trail:'#ffc1d3',death:[784,659,523,392,330]}, mint:{name:'MINT',cost:50,body:'#75e6c8',wing:'#35bd9d',beak:'#ffa94d',trail:'#b7fff0',death:[659,784,880,659,523]}, night:{name:'NIGHT',cost:90,body:'#8496ff',wing:'#576dcb',beak:'#e6b4ff',trail:'#d4c7ff',death:[1047,784,698,523,349]} };
  const pipeSkins = { green:{name:'GREEN',cost:0,body:'#287a55',wing:'#3dbb68',edge:'#216c4d',cap:'#53d878'}, candy:{name:'CANDY',cost:35,body:'#b85c87',wing:'#ff91b8',edge:'#81405d',cap:'#ffb4cf'}, neon:{name:'NEON',cost:80,body:'#3863a8',wing:'#5be6e0',edge:'#1c3677',cap:'#83fff5'} };
  const backgrounds = { sky:{name:'SKY',cost:0,top:'#72caed',bottom:'#d3f3f4',hill:'#75bb9b'}, sunset:{name:'SUNSET',cost:45,top:'#f89b75',bottom:'#ffe5a6',hill:'#c47772'}, space:{name:'SPACE',cost:100,top:'#182858',bottom:'#4c4a8c',hill:'#393c77'} };
  const tracks = { happy:{name:'HAPPY',cost:0,color:'#ffbf38',notes:[523,659,784,659,587,698,880,698]}, bounce:{name:'BOUNCE',cost:55,color:'#f287b5',notes:[659,784,880,784,698,784,1047,880]}, arcade:{name:'ARCADE',cost:110,color:'#7c8dff',notes:[392,523,659,784,659,523,440,523]} };
  const progress = storage.get('skyFlappyProgress', { coins:0, unlocked:['classic'], selected:'classic' });
  if(!Array.isArray(progress.unlocked))progress.unlocked=['classic'];if(!skins[progress.selected])progress.selected='classic';if(typeof progress.coins!=='number')progress.coins=0;for(const [key,catalog,free] of [['pipe',pipeSkins,'green'],['background',backgrounds,'sky'],['music',tracks,'happy']]){if(!Array.isArray(progress[key+'Unlocked']))progress[key+'Unlocked']=[free];if(!catalog[progress['selected'+key[0].toUpperCase()+key.slice(1)]])progress['selected'+key[0].toUpperCase()+key.slice(1)]=free;}
  let best = storage.get('skyFlappyBest', 0), state = State.MENU, last = 0, started = false, score = 0, pipes = [], coins = [], flyers = [], particles = [], spawn = 0, flyerSpawn = 0, trailSpawn = 0, groundX = 0, cloudX = 0, shake = 0, overTimer = 0, lastGapY = 300;
  const bird = { x:104, y:280, vy:0, r:16, wing:0, angle:0, dead:false };
  const audio = { ctx:null, musicTimer:null, deathTimer:null, init() { if (!this.ctx) this.ctx = new (window.AudioContext || window.webkitAudioContext)(); if(this.ctx.state==='suspended') this.ctx.resume().catch(()=>{}); }, tone(freq, dur=.1, type='sine', volume=.05, slide=0) { if(!settings.sound) return; this.playTone(freq,dur,type,volume,slide); }, playTone(freq, dur, type, volume, slide=0) { try { this.init(); const t=this.ctx.currentTime, o=this.ctx.createOscillator(), g=this.ctx.createGain(); o.type=type;o.frequency.setValueAtTime(freq,t);o.frequency.exponentialRampToValueAtTime(Math.max(20,freq+slide),t+dur);g.gain.setValueAtTime(volume,t);g.gain.exponentialRampToValueAtTime(.001,t+dur);o.connect(g).connect(this.ctx.destination);o.start(t);o.stop(t+dur); } catch(_){} }, flap(){this.tone(520,.07,'triangle',.035,180)}, score(){this.tone(760,.13,'sine',.05,260)}, hit(){this.tone(130,.2,'sawtooth',.06,-70)}, click(){this.tone(360,.045,'square',.025,70)}, win(){this.tone(660,.16,'triangle',.05,500)}, music(){ if(!settings.music || this.musicTimer) return; const melody=[523,659,784,659,587,698,880,698,659,784,1047,784,698,880,1047,880,523,659,784,1047,988,880,784,659,587,698,784,698,659,587,523,0]; const bass=[131,0,131,0,147,0,147,0,165,0,165,0,147,0,147,0]; let step=0; this.init(); this.musicTimer=setInterval(()=>{ if(state!==State.PLAYING)return; const note=melody[step%melody.length], low=bass[Math.floor(step/2)%bass.length]; if(note)this.playTone(note,.19,'triangle',.018); if(low)this.playTone(low,.32,'sine',.026); if(step%4===2)this.playTone(1046,.045,'square',.006); step++; },190); }, deathMusic(){ if(!settings.music) return; clearInterval(this.deathTimer); const notes=[523,494,440,349,262]; let step=0; const play=()=>{ if(step>=notes.length){clearInterval(this.deathTimer);this.deathTimer=null;return;} this.playTone(notes[step++],.24,'triangle',.025,-20); }; play(); this.deathTimer=setInterval(play,170); }, stopMusic(){clearInterval(this.musicTimer);clearInterval(this.deathTimer);this.musicTimer=null;this.deathTimer=null;} };
  audio.deathMusic=()=>{if(!settings.sound)return;clearInterval(audio.deathTimer);const notes=(skins[progress.selected]||skins.classic).death;let step=0;const play=()=>{if(step>=notes.length){clearInterval(audio.deathTimer);audio.deathTimer=null;return;}audio.playTone(notes[step++],.28,'triangle',.055,-35);};play();audio.deathTimer=setInterval(play,235);};
  audio.music=()=>{if(!settings.music||audio.musicTimer)return;const notes=(tracks[progress.selectedMusic]||tracks.happy).notes;let step=0;audio.init();audio.musicTimer=setInterval(()=>{if(state!==State.PLAYING)return;const note=notes[step%notes.length];audio.playTone(note,.19,'triangle',.018);if(step%2===0)audio.playTone(note/4,.3,'sine',.022);if(step%4===2)audio.playTone(note*2,.04,'square',.006);step++;},190);};
  function persist(){storage.set('skyFlappySettings',settings)}
  function persistProgress(){storage.set('skyFlappyProgress',progress)}
  function updateCoins(){el.coinHud.innerHTML='COINS <b>'+progress.coins+'</b>';el.coinCount.textContent=progress.coins;el.shopCoins.textContent=progress.coins;}

  // Background music control (HTML5 audio fallback)
  function playBackgroundMusic(){try{const bg=document.getElementById('bgMusic');if(!bg) return; if(!settings.music) return; bg.volume = 0.45; const p = bg.play(); if(p && typeof p.catch === 'function') p.catch(()=>{});}catch(_){}
  }
  function stopBackgroundMusic(){try{const bg=document.getElementById('bgMusic');if(!bg) return; bg.pause(); bg.currentTime = 0;}catch(_){}
  }
  function updateMusicUI(){const button=el.musicBtn;if(!button)return;button.innerHTML=settings.music?'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9 18V6l9-2v12"/><path d="M9 18a3 3 0 1 1-3-3 3 3 0 0 1 3 3ZM18 16a3 3 0 1 1-3-3 3 3 0 0 1 3 3Z"/></svg>':'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9 18V6l9-2v12"/><path d="M9 18a3 3 0 1 1-3-3 3 3 0 0 1 3 3ZM18 16a3 3 0 1 1-3-3 3 3 0 0 1 3 3Z"/><path d="m4 4 16 16"/></svg>';button.setAttribute('aria-label',settings.music?'Matikan musik':'Nyalakan musik');}
  if(el.musicToggle) el.musicToggle.onchange = (e)=>{ settings.music = e.target.checked; syncSettings(); updateMusicUI(); persist(); };
  let shopCategory='bird';
  function shopCatalog(){return shopCategory==='bird'?skins:shopCategory==='pipe'?pipeSkins:shopCategory==='background'?backgrounds:tracks;}
  function shopKeys(){return shopCategory==='bird'?['unlocked','selected']:[shopCategory+'Unlocked','selected'+shopCategory[0].toUpperCase()+shopCategory.slice(1)];}
  function renderShop(){
    const [unlockedKey,selectedKey]=shopKeys(),catalog=shopCatalog(),preview=shopCategory==='bird'?'':shopCategory==='pipe'?'pipe-preview':shopCategory==='background'?'bg-preview':'music-preview';
    el.shopTabs.querySelectorAll('[data-shop-category]').forEach(tab=>tab.classList.toggle('active',tab.dataset.shopCategory===shopCategory));
    el.skinList.innerHTML = Object.entries(catalog).map(([id,item])=>{
      const unlocked = progress[unlockedKey].includes(id), selected = progress[selectedKey]===id;
      const body = item.body||item.top||item.color, wing = item.wing||item.bottom||item.color;
      const cap = item.cap||body, edge = item.edge||wing, top = item.top||body, bottom = item.bottom||wing, color = item.color||body;
      return '<button class="skin-card '+(selected?'selected ':'')+(unlocked?'':'locked')+'" data-product="'+id+'" style="--body:'+body+';--wing:'+wing+';--beak:'+(item.beak||body)+';--cap:'+cap+';--edge:'+edge+';--top:'+top+';--bottom:'+bottom+';--color:'+color+'">' +
        '<span class="skin-preview '+preview+'"></span><span>'+item.name+'</span><span class="skin-cost">'+(selected?'EQUIPPED':unlocked?'USE':'🪙 '+item.cost)+'</span></button>';
    }).join('');
    el.skinList.querySelectorAll('[data-product]').forEach(button=>button.onclick=()=>buyProduct(button.dataset.product));
  }
  function buyProduct(id){const [unlockedKey,selectedKey]=shopKeys(),item=shopCatalog()[id];if(progress[unlockedKey].includes(id)){progress[selectedKey]=id;audio.click();}else if(progress.coins>=item.cost){progress.coins-=item.cost;progress[unlockedKey].push(id);progress[selectedKey]=id;audio.win();}else{audio.hit();return;}persistProgress();updateCoins();renderShop();if(shopCategory==='music'&&state===State.PLAYING){audio.stopMusic();audio.music();}}
  function showModal(modal) { el.layer.classList.remove('hidden'); [el.how,el.settings,el.shop,el.paused,el.over].forEach(x=>x.classList.add('hidden')); modal.classList.remove('hidden'); }
  function closeModal(){el.layer.classList.add('hidden');}
  function setState(next){state=next;el.menu.classList.toggle('hidden',next!==State.MENU);el.ready.classList.toggle('hidden',next!==State.READY);el.hud.classList.toggle('hidden',next===State.MENU);el.pause.style.display=(next===State.PLAYING||next===State.READY)?'block':'none';el.sound.style.display=(next===State.MENU||next===State.PLAYING||next===State.READY)?'block':'none';}
  function reset(){ score=0; pipes=[];coins=[];flyers=[];particles=[];spawn=0;flyerSpawn=0;trailSpawn=0;groundX=0;shake=0;started=false;lastGapY=300;el.over.classList.remove('visible');Object.assign(bird,{x:104,y:285,vy:0,wing:0,angle:0,dead:false});updateScore(); }
  function goReady(){audio.click();closeModal();reset();setState(State.READY)}
  function flap(){ if(state===State.MENU) return; if(state===State.OVER) return; if(state===State.PAUSED) return; if(state===State.READY){ started=true; setState(State.PLAYING); audio.music(); playBackgroundMusic(); } bird.vy=-310; bird.wing=.18; makeParticles(bird.x-12,bird.y,4,'#fff5b2'); audio.flap(); }
  function makePipe(){ const d=settings.difficulty, level=Math.floor(score/5), gapBase=d==='easy'?164:d==='hard'?132:148, gap=Math.max(96,gapBase-level*4); const margin=72, max=H-GROUND-gap-margin; let y=margin+Math.random()*(max-margin); y=Math.max(margin,Math.min(max,(y+lastGapY)/2+(Math.random()-.5)*95));lastGapY=y;const pipe={x:W+28,gapY:y,gapSize:gap,w:60,passed:false};pipes.push(pipe);if(Math.random()<.7)coins.push({x:pipe.x+pipe.w/2,y:pipe.gapY+pipe.gapSize/2,r:10,spin:Math.random()*6}); }
  function makeFlyer(){flyers.push({x:W+35,y:125+Math.random()*(H-GROUND-205),r:15,wing:Math.random()*6,speed:1.05+Math.random()*.18});}
  function updateScore(){el.score.textContent=score;el.best.textContent=best;}
  function addScore(){score++;updateScore();el.score.classList.remove('bump');void el.score.offsetWidth;el.score.classList.add('bump');el.pop.classList.remove('show');void el.pop.offsetWidth;el.pop.classList.add('show');makeParticles(180,76,9,'#fff0a8');audio.score(); if(score===10||score===25||score===50) makeParticles(180,180,25,'#ffe45c');}
  function makeParticles(x,y,count,color){for(let i=0;i<count;i++)particles.push({x,y,vx:(Math.random()-.5)*100,vy:(Math.random()-.8)*100,life:.55+Math.random()*.35,color,size:2+Math.random()*3});}
  function skinTrail(dt){const skin=skins[progress.selected]||skins.classic;trailSpawn+=dt;if(trailSpawn<.11)return;trailSpawn=0;particles.push({x:bird.x-15,y:bird.y+7,vx:-70-Math.random()*45,vy:(Math.random()-.5)*35,life:.35+Math.random()*.18,color:skin.trail,size:2+Math.random()*3});}
  function collide(p){ const bx=bird.x,by=bird.y, r=bird.r*.72; if(bx+r>p.x&&bx-r<p.x+p.w&&(by-r<p.gapY||by+r>p.gapY+p.gapSize)) return true; return false; }
  // end game: stop synth and HTML5 background music, play death music
  function endGame(){ if(state===State.OVER) return; state=State.OVER; bird.dead=true; shake=.26; audio.hit(); audio.stopMusic(); stopBackgroundMusic(); audio.deathMusic(); if(navigator.vibrate&&settings.vibration) navigator.vibrate(80); const newBest = score>best; if(newBest){ best=score; storage.set('skyFlappyBest',best); audio.win(); } updateScore(); overTimer=.65; }
  function update(dt){cloudX=(cloudX+10*dt)%W;if(state===State.READY){bird.y=285+Math.sin(performance.now()/250)*7;bird.wing=.1;return;} if(state===State.OVER){bird.vy=Math.min(420,bird.vy+850*dt);bird.y+=bird.vy*dt;bird.angle=Math.min(1.6,bird.angle+3*dt);overTimer-=dt;if(overTimer<=0&&!el.over.classList.contains('visible')) showOver();return;} if(state!==State.PLAYING)return;
    bird.vy=Math.min(430,bird.vy+830*dt);bird.y+=bird.vy*dt;bird.wing=Math.max(0,bird.wing-dt);bird.angle=Math.max(-.42,Math.min(1.05,bird.vy/520));const level=Math.min(10,Math.floor(score/5)), speed=Math.min(225,115+level*10+(settings.difficulty==='easy'?-12:settings.difficulty==='hard'?13:0)), spawnDelay=Math.max(.98,1.58-level*.05);spawn+=dt;flyerSpawn+=dt;if(spawn>spawnDelay){spawn=0;makePipe()}if(score>=12&&flyerSpawn>Math.max(5.8,8-level*.18)){flyerSpawn=0;makeFlyer()}for(const p of pipes){p.x-=speed*dt;if(!p.passed&&p.x+p.w<bird.x-bird.r){p.passed=true;addScore()}if(collide(p))endGame()}pipes=pipes.filter(p=>p.x+p.w>-8);for(const flyer of flyers){flyer.x-=(speed*flyer.speed+45)*dt;flyer.wing+=dt*12;if(Math.hypot(bird.x-flyer.x,bird.y-flyer.y)<bird.r*.72+flyer.r*.72)endGame()}flyers=flyers.filter(flyer=>flyer.x+flyer.r>-10);for(const coin of coins){coin.x-=speed*dt;coin.spin+=dt*7;if(Math.hypot(bird.x-coin.x,bird.y-coin.y)<bird.r+coin.r){coin.collected=true;progress.coins++;persistProgress();updateCoins();makeParticles(coin.x,coin.y,12,'#ffe56b');audio.score();}}coins=coins.filter(coin=>!coin.collected&&coin.x+coin.r>-8);if(bird.y-bird.r<0||bird.y+bird.r>H-GROUND)endGame();groundX=(groundX+speed*dt)%30;
    skinTrail(dt);for(const q of particles){q.x+=q.vx*dt;q.y+=q.vy*dt;q.vy+=100*dt;q.life-=dt}particles=particles.filter(q=>q.life>0);
  }
  function rr(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill();}
  function render(){ctx.save();if(shake>0){ctx.translate((Math.random()-.5)*7,(Math.random()-.5)*7);shake-=1/60}const bg=backgrounds[progress.selectedBackground]||backgrounds.sky,sky=ctx.createLinearGradient(0,0,0,H);sky.addColorStop(0,bg.top);sky.addColorStop(1,bg.bottom);ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);drawCloud(cloudX-45,105,1);drawCloud(cloudX+190,170,.7);drawHills();for(const p of pipes)drawPipe(p);for(const coin of coins)drawCoin(coin);for(const flyer of flyers)drawFlyer(flyer);for(const q of particles){ctx.globalAlpha=Math.max(0,q.life);ctx.fillStyle=q.color;ctx.fillRect(q.x,q.y,q.size,q.size)}ctx.globalAlpha=1;drawGround();drawBird();ctx.restore();}
  function drawCloud(x,y,s){ctx.save();ctx.translate(x,y);ctx.scale(s,s);ctx.fillStyle='#ffffffa8';for(const [a,b,r] of [[0,10,14],[16,3,19],[36,13,13],[-17,15,10]]){ctx.beginPath();ctx.arc(a,b,r,0,7);ctx.fill()}ctx.fillRect(-17,15,66,13);ctx.restore();}
  function drawHills(){const bg=backgrounds[progress.selectedBackground]||backgrounds.sky;ctx.fillStyle=bg.hill;ctx.beginPath();ctx.moveTo(0,H-GROUND-45);for(let x=0;x<=W;x+=45)ctx.quadraticCurveTo(x+20,H-GROUND-105+(x%90?22:0),x+45,H-GROUND-45);ctx.lineTo(W,H-GROUND);ctx.lineTo(0,H-GROUND);ctx.fill();ctx.fillStyle='#4aa474';ctx.beginPath();ctx.moveTo(0,H-GROUND-20);for(let x=0;x<=W;x+=55)ctx.quadraticCurveTo(x+30,H-GROUND-68,x+55,H-GROUND-20);ctx.lineTo(W,H-GROUND);ctx.lineTo(0,H-GROUND);ctx.fill();}
  function drawPipe(p){const cap=11,skin=pipeSkins[progress.selectedPipe]||pipeSkins.green;ctx.save();ctx.fillStyle=skin.body;rr(p.x,0,p.w,p.gapY-cap,5);rr(p.x,p.gapY+p.gapSize+cap,p.w,H-(p.gapY+p.gapSize+cap),5);ctx.fillStyle=skin.wing;ctx.fillRect(p.x+5,0,12,p.gapY-cap);ctx.fillRect(p.x+5,p.gapY+p.gapSize+cap,12,H);ctx.fillStyle=skin.edge;ctx.fillRect(p.x+p.w-8,0,8,p.gapY-cap);ctx.fillRect(p.x+p.w-8,p.gapY+p.gapSize+cap,8,H);ctx.fillStyle=skin.cap;rr(p.x-5,p.gapY-cap,p.w+10,cap,3);rr(p.x-5,p.gapY+p.gapSize,p.w+10,cap,3);ctx.restore();}
  function drawCoin(coin){ctx.save();ctx.translate(coin.x,coin.y);ctx.scale(.8+Math.abs(Math.sin(coin.spin))*.2,1);ctx.fillStyle='#d99014';ctx.beginPath();ctx.arc(0,0,coin.r,0,7);ctx.fill();ctx.fillStyle='#ffdc4e';ctx.beginPath();ctx.arc(0,-1,coin.r-2,0,7);ctx.fill();ctx.fillStyle='#fff1a0';ctx.fillRect(-1,-6,3,11);ctx.fillRect(-5,-2,11,3);ctx.restore();}
  function drawFlyer(flyer){ctx.save();ctx.translate(flyer.x,flyer.y);ctx.scale(-1,1);ctx.fillStyle='#e85d50';ctx.beginPath();ctx.ellipse(0,0,flyer.r,flyer.r*.72,0,0,7);ctx.fill();ctx.fillStyle='#c83f43';ctx.save();ctx.rotate(Math.sin(flyer.wing)*.55);ctx.beginPath();ctx.ellipse(-4,-8,10,5,-.45,0,7);ctx.fill();ctx.restore();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(6,-5,4,0,7);ctx.fill();ctx.fillStyle='#16365d';ctx.beginPath();ctx.arc(7,-5,1.5,0,7);ctx.fill();ctx.fillStyle='#ffbe45';ctx.beginPath();ctx.moveTo(14,0);ctx.lineTo(23,4);ctx.lineTo(14,7);ctx.fill();ctx.restore();}
  function drawGround(){const y=H-GROUND;ctx.fillStyle='#46b65c';ctx.fillRect(0,y,W,9);ctx.fillStyle='#b57a45';ctx.fillRect(0,y+9,W,GROUND);ctx.fillStyle='#e6ad5a';ctx.fillRect(0,y+11,W,5);ctx.fillStyle='#8b5939';for(let x=-groundX;x<W;x+=30){ctx.fillRect(x,y+28,13,3);ctx.fillRect(x+16,y+54,9,3)}ctx.fillStyle='#72df6c';for(let x=-groundX;x<W;x+=15){ctx.fillRect(x,y-4,6,5)}}
  function drawBird(){const skin=skins[progress.selected]||skins.classic;ctx.save();ctx.translate(bird.x,bird.y);ctx.rotate(bird.angle);ctx.fillStyle='#de7c24';ctx.beginPath();ctx.ellipse(-18,3,11,8,0,0,7);ctx.fill();ctx.fillStyle=skin.body;ctx.beginPath();ctx.ellipse(0,0,18,15,0,0,7);ctx.fill();ctx.fillStyle=skin.wing;ctx.beginPath();ctx.ellipse(-4,6,9,6,0,0,7);ctx.fill();ctx.fillStyle='#fff1af';ctx.beginPath();ctx.ellipse(-5,5,7,4,.2,0,7);ctx.fill();ctx.fillStyle=skin.beak;ctx.beginPath();ctx.moveTo(15,-2);ctx.lineTo(28,3);ctx.lineTo(15,8);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(6,-7,6,0,7);ctx.fill();ctx.fillStyle='#193550';ctx.beginPath();ctx.arc(8,-7,2.4,0,7);ctx.fill();ctx.restore();}
  function showOver(){el.over.classList.add('visible');el.finalScore.textContent=score;el.finalBest.textContent=best;const nb=score>=best&&score>0;el.newBest.classList.toggle('hidden',!nb);el.medal.className='medal '+(score>=100?'diamond':score>=50?'gold':score>=25?'silver':score>=10?'bronze':'');showModal(el.over);}
  function pause(){ if(state===State.PLAYING||state===State.READY){ state=State.PAUSED; audio.stopMusic(); stopBackgroundMusic(); showModal(el.paused); } }
  function resume(){ closeModal(); state = started ? State.PLAYING : State.READY; if(started){ audio.music(); playBackgroundMusic(); } }
  function home(){ audio.stopMusic(); stopBackgroundMusic(); closeModal(); reset(); setState(State.MENU); }
  $('playBtn').onclick=goReady;$('howBtn').onclick=()=>{audio.click();showModal(el.how)};$('settingsBtn').onclick=()=>{audio.click();showModal(el.settings)};$('shopBtn').onclick=()=>{audio.click();updateCoins();renderShop();showModal(el.shop)};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{audio.click();closeModal()});$('resumeBtn').onclick=resume;$('restartBtn').onclick=goReady;$('homeBtn').onclick=home;$('replayBtn').onclick=goReady;$('overHomeBtn').onclick=home;el.pause.onclick=pause;el.sound.onclick=()=>{settings.sound=!settings.sound;el.soundToggle.checked=settings.sound;syncSettings();audio.click()};el.musicBtn.onclick=()=>{settings.music=!settings.music;el.musicToggle.checked=settings.music;syncSettings();audio.click(); if(settings.music && state===State.PLAYING) playBackgroundMusic(); else stopBackgroundMusic(); persist(); };
  // shop tab clicks
  if(el.shopTabs) el.shopTabs.querySelectorAll('[data-shop-category]').forEach(tab=>tab.onclick=()=>{ shopCategory = tab.dataset.shopCategory; renderShop(); });
  function syncSettings(){el.soundToggle.checked=settings.sound;el.musicToggle.checked=settings.music;el.difficultyValue.textContent=settings.difficulty.toUpperCase();el.difficultyMenu.querySelectorAll('[data-difficulty]').forEach(button=>button.classList.toggle('active',button.dataset.difficulty===settings.difficulty));el.sound.innerHTML=settings.sound?'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 10v4h3l4 3V7l-4 3H4Z"/><path d="M15 9.25a4 4 0 0 1 0 5.5M17.5 6.75a7.5 7.5 0 0 1 0 10.5"/></svg>':'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 10v4h3l4 3V7l-4 3H4Z"/><path d="m15 10 5 5m0-5-5 5"/></svg>';el.sound.setAttribute('aria-label',settings.sound?'Matikan suara':'Nyalakan suara');updateMusicUI();persist();if(!settings.music)audio.stopMusic();else if(state===State.PLAYING)audio.music();}function closeDifficulty(){el.difficultyMenu.classList.add('hidden');el.difficultyBtn.setAttribute('aria-expanded','false');}el.soundToggle.onchange=e=>{settings.sound=e.target.checked;syncSettings()};el.musicToggle.onchange=e=>{settings.music=e.target.checked;syncSettings()};el.difficultyBtn.onclick=()=>{const open=el.difficultyMenu.classList.toggle('hidden');el.difficultyBtn.setAttribute('aria-expanded',String(!open));};el.difficultyMenu.querySelectorAll('[data-difficulty]').forEach(button=>button.onclick=()=>{settings.difficulty=button.dataset.difficulty;audio.click();syncSettings();closeDifficulty();});document.addEventListener('pointerdown',e=>{if(!e.target.closest('.difficulty-picker'))closeDifficulty();});
  window.addEventListener('keydown',e=>{if(['Space','ArrowUp'].includes(e.code)){e.preventDefault();flap()}if((e.code==='KeyP'||e.code==='Escape')&&(state===State.PLAYING||state===State.READY))pause();else if((e.code==='KeyP'||e.code==='Escape')&&state===State.PAUSED)resume()});canvas.addEventListener('pointerdown',e=>{e.preventDefault();flap()});el.ready.addEventListener('pointerdown',e=>{e.preventDefault();flap()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&(state===State.PLAYING||state===State.READY))pause()});
  function loop(t){const dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt);render();requestAnimationFrame(loop)}syncSettings();updateCoins();renderShop();reset();setState(State.MENU);updateMusicUI();requestAnimationFrame(loop);
})();
